# Generated by Django 4.1.7 on 2023-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCD_app", "0003_alter_uploadimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="detect-images/",
                        verbose_name="detected-image",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NameTester",
        ),
        migrations.AlterField(
            model_name="uploadimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pig-images/", verbose_name="image"
            ),
        ),
    ]
